#!/bin/bash
# shellcheck disable=SC1090,SC1091

# bashrc is executed for all interactive bash shells, but macos seems to prefer
# bash_profile these days...
#
# I use zsh so this is just for in case I need to go in there for some reason
# make sure some important stuff works?


# source all homebrew provided completions for bash
# https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash
if type brew &>/dev/null
then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi

# ultra simple shell prompt, since I use bash mostly for CLI app screenshots and
# dont want any personalized info
export PS1="\[\e[2m\]$\[\e[0m\] "
